import { Hero, TextWithMedia } from 'components/block';
import { MainLayout } from 'components/layout';
import { useTranslation } from 'lib/utils/i18n/useTranslation';
import Head from 'next/head';
import HeroImage from 'public/media/images/hero1.jpg';
import Team from 'public/media/images/team1.jpg';
import { NextPageWithLayout } from './page';

const Home: NextPageWithLayout = () => {
  const activitiesId = 'activities';
  const { t } = useTranslation();

  const scrollTo = (id: string) => {
    const el = document.getElementById(id);
    el && el.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        eyebrow={t('make-a-difference')}
        title={t('you-can-help')}
        ctaText={t('what-are-we-doing')}
        ctaCallback={() => scrollTo(activitiesId)}
        backgroundImage={HeroImage}
      />
      <TextWithMedia
        title={t('who-are-we')}
        text={t('who-is-edplus')}
        image={Team}
      />
    </>
  );
};

Home.getLayout = (page) => {
  return <MainLayout>{page}</MainLayout>;
};

export default Home;
