import { MainLayout } from 'components/layout';
import { Title } from 'components/shared';
import { TITLE_TYPES } from 'lib/utils/constants';
import Head from 'next/head';
import { NextPageWithLayout } from './page';

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title title={'hey'} type={TITLE_TYPES.h3} level={TITLE_TYPES.h1} />
    </>
  );
};

Home.getLayout = (page) => {
  return <MainLayout>{page}</MainLayout>;
};

export default Home;
